{% set name = "fsleyes-props" %}
{% set version = "1.11.0" %}
{% set sha256 = "10de337569575c9a6afc41f848641c115e46950c1e84074fdf930d7be1401c6e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base >=3.5
    - wxpython >=3.0.2.0
    - fsleyes-widgets >=0.6
    - fslpy >=1.4

test:
  source_files:
    - fsleyes_props/tests
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
  commands:
    - xvfb-run -s "-screen 0 640x480x24" pytest -v --cov=fsleyes_props


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: '[wx]Python event programming framework'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/

extra:
  recipe-maintainers:
    - pauldmccarthy
