{% set name = "fsleyes-props" %}
{% set version = "1.12.3" %}
{% set sha256 = "9fbc1a7940ed0235cfcee7e2e5bfed34857eebd1c84fa82bc91c4266016dec67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base >=3.5
    - wxpython >=3.0.2.0
    - fsleyes-widgets >=0.6
    - fslpy >=1.4

test:
  source_files:
    - fsleyes_props/tests
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
    - python {{ python_min }}
  commands:
    - xvfb-run -s "-screen 0 640x480x24" pytest -v --cov=fsleyes_props


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: '[wx]Python event programming framework'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/

extra:
  recipe-maintainers:
    - pauldmccarthy
