{% set name = "fsleyes-props" %}
{% set version = "1.9.4" %}
{% set sha256 = "e5c3c0f4c191228456f256e49cb980455f66d130f17b13cb69a21eca9e2ac533" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - matplotlib-base >=3.5
    - six
    - wxpython >=3.0.2.0
    - fsleyes-widgets >=0.6
    - fslpy >=1.4

test:
  source_files:
    - tests
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
  commands:
    - xvfb-run -s "-screen 0 640x480x24" pytest -v --cov=fsleyes_props


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: '[wx]Python event programming framework'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/

extra:
  recipe-maintainers:
    - pauldmccarthy
