travis:
  secure:
    BINSTAR_TOKEN: TjOdd65lESSpgFHA1GZFVOkC5vVmgpfTOb8LVoh40nIz4lUYue4Pw/iZczCm/vlOC9lkcqS/URnom2IKYk9m/6rPGlIj2vGgvwZQkr9CmvBH+RKw9AzOo9146f7FT5QkXlkcS0lITA85NucxeEbiRU1TRfaSa100or36pSIWNcfBE9H2CMU9WQJWm5zZcxjl5rIMB5p9ao67WPn9oyyXTzn/pXhiPQT/+05KGn9hJiV+S/g26/+SZo1Cbi7ZvL+28E80ZH8ilh8sRBJ3gFEy7DqaoUaVD0LgvkXur6ICXY4ri3Yd7OlAOrBPTS0neSy77F40oJuaffx7TJgDFgYov8C17PCxXv3UO2+LgIdmtXOyVUh6CC7UKJA68K/wpw98f+CPK/c3xUJcELMxBlGKJfRpBNhdV0+oQQPyheXBnZx3o2Xr5N48NSFVSftVJj9Rva/PbUlwRPhLa/EDww3T9lO6/AARePoWdmeFpXU8I0PhExhKAaCPDY5nyP94JDyfuM/VrgXqRZNYhwDxw9S/B7Lah9lty9KwZutJXa8vwD1okaTVLd7AUQaISpZ2x7ybi8WbkDVYxi9ZW+/PFO8fFNqbuEI/CKTOqRdv8jC/gf465/t7QE2WzuzACpsUlbUYTxm1FsCjwSKhENpdV7LHK/thfqwIpM6vJ02ib4GTKIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
